# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="eastwood"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git last-working-dir macports osx)

source $ZSH/oh-my-zsh.sh

# colorgcc must be before /usr/bin
export PATH=/Users/Ben/dev/colorgcc:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/sphinx/bin:/opt/local/share/java/android-sdk-macosx/platform-tools:/opt/local/share/java/android-sdk-macosx/tools:/opt/local/share/java/android-sdk-macosx:/usr/local/Trolltech/Qt-4.7.4/bin:/Users/Ben/projects/scivey.com/app/Console:/Applications/MAMP/bin/php5/bin:/Applications/MAMP/Library/bin:/opt/local/bin:/opt/local/sbin:/Applications/Postgres.app/Contents/MacOS/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/X11/bin

# OGRE3D
export PATH=/Users/Ben/dev/OgreSDK/bin:/Users/Ben/dev/OgreSDK/lib:/Users/Ben/dev/OgreSDK/include:$PATH

# rupa z jumper
. /Users/Ben/dev/z/z.sh

# zsh-syntax-highlighting
source /Users/Ben/dev/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias matlab='/Applications/MATLAB_R2011b.app/bin/matlab -nodesktop -nosplash'
alias iphone='open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app'
alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'


# these stuff are required to display Unicode characters in terminal for all
# apps (vim, less, etc)
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8

# VIM mode
#bindkey -v
#bindkey -M viins 'jk' vi-cmd-mode
#bindkey -M viins 'kj' vi-cmd-mode
#bindkey '^R' history-incremental-search-backward
